development:
  dialect: postgres
  database: bookmyroom
  user: postgres
  password: adi123
  host: postgres
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@postgres:5432/myapp_test"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@postgres:5432/myapp_production"}}