development:
  dialect: postgres
  database: bookmyroom
  user: postgres
  password: IMNKyIMdKVtc4bfFloaD
  host: bookmyroom.ckzlaalx1suy.ap-south-1.rds.amazonaws.com
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@bookmyroom.ckzlaalx1suy.ap-south-1.rds.amazonaws.com:5432/myapp_test"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@bookmyroom.ckzlaalx1suy.ap-south-1.rds.amazonaws.com:5432/myapp_production"}}