name: ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: adi123
          POSTGRES_DB: bookmyroom
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v2.0
      with:
        envkey_DB_NAME: bookmyroom
        envkey_DB_USER: postgres
        envkey_DB_PASS: adi123
        envkey_DB_HOST: localhost
        envkey_DB_PORT: 5432
        envkey_SSL_MODE: disable
        envkey_PRODUCTION: true
        envkey_CACHE: true
        directory: /home/runner/work/bookmyroom/cmd/web
        file_name: .env

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Test
      run: make test